---
title: "Workout 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r download, echo=FALSE}
andre = 'https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/andre-iguodala.csv'
draymond = 'https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/draymond-green.csv'
kevin = 'https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/kevin-durant.csv'
klay = 'https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/klay-thompson.csv'
stephen = 'https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/stephen-curry.csv'
#download.file(andre, 'andre-iguodala.csv')
#download.file(draymond, 'draymond-green.csv')
#download.file(kevin, 'kevin-durant.csv')
#download.file(klay, 'klay-thompson.csv')
#download.file(stephen, 'stephen-curry.csv')
```

#2PT Effective Shooting % by Player
```{r chart1, echo=FALSE, message = FALSE}
library(dplyr)
library(gridExtra)
shotsData = read.csv('../data/shots-data.csv', header = TRUE, sep = ",")
twoPointEffective = arrange(summarise(
  group_by(shotsData, name), 
  total = sum(name == name & shot_type == '2PT Field Goal'), 
  made = sum(shot_made_flag == 'shot_yes' & shot_type == '2PT Field Goal'), 
  perc_made = made/total), desc(perc_made))
grid.table(twoPointEffective)
```

#3PT Effective Shooting % by Player
```{r chart2, echo=FALSE, message = FALSE}
shotsData = read.csv('../data/shots-data.csv', header = TRUE, sep = ",")
threePointEffective = arrange(summarise(
  group_by(shotsData, name), 
  total = sum(name == name & shot_type == '3PT Field Goal'), 
  made = sum(shot_made_flag == 'shot_yes' & shot_type == '3PT Field Goal'), 
  perc_made = made/total), desc(perc_made))
grid.table(threePointEffective)
```

#Effective Shooting % by Player
```{r chart3, echo=FALSE, message = FALSE}
shotsData = read.csv('../data/shots-data.csv', header = TRUE, sep = ",")
effective = arrange(summarise(
  group_by(shotsData, name), 
  total = sum(name == name), 
  made = sum(shot_made_flag == 'shot_yes'), 
  perc_made = made/total), desc(perc_made))
grid.table(effective)
```